# '_config.yml'
# Author/CopyRight: Mancuso, Logan
# Last Edit Date: 05-01-2019--16:27:49

# Site
title:              Logan Mancuso
bio:                'Computer Science & Mathematics'
description:        "B.S. with a focus in Graph Theory"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loganmancuso.github.io/" # the base hostname & protocol for your site

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
github:             loganmancuso
gitlab:             loganmancuso

# personal
location:           Blythewood, SC
phone:              803-348-5862
email:              logan@mancuso.in # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/background.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: blog
    author: Logan Mancuso

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://loganmancuso.github.io/

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, 
            package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
