# Site
repository: loganmancuso/loganmancuso.github.io
favicon: assets/images/favicon.ico

# Personal info
name: Logan Mancuso
title: DevOps Engineer and Systems Administator
email: logan@mancuso.in
phone: +1 (803) 470-3985
# website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  loganmancuso
gitlab_username: loganmancuso
stackoverflow_username: "9565035"
linkedin_username: mancuso.logan

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/profile.jpg
about_content: | 
  I have grown up around technology and with this exposure came an increased interest in problem solving.
  Breaking down complex problems into their core compenents is one of my greatest interests when it comes to software development.
  Studying computer sience and mathematics at UofSC gave me the opportunity to delve into complex data analysis and neural network design.
   
  *Independent work*
    - Complex scripting shortcuts for BASH environments to improve usability of the Linux platform
    - Data Visualization using PowerBI 

# Projects Section
#projects_title: Projects #(Use this to override about projects section title)

# Experience Section
#experience_title: Experience #(Use this to override about experience section title)

# Education Section
#education_title: Education #(Use this to override about education section title)

# More Section
more_title: Skills #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  Python/Java/C#/Go/C++
    - OOP design and implementation 
  MySQL/MariaDB/PostgreSQL
    - Database management and development
  OpenCV/TensorFlow/OpenMPi/Anaconda
    - Machine learning and AI development
  BASH/PowerShell/SLURM/Ruby/Perl
    - Schedule processing and resource allocation
  Team/Independent Environment
    - Coding projects independently and contribute to a larger scale project
  Mathematics background 
    - Analysis of algorithmic efficiency multi node process scaling
  PHP/CSS/HTML/d3

#  This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.
# Footer

footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
