# Site settings
title: "Resume"
description: "A resume for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Logan Mancuso"
resume_title:                   "IaC DevSecOps & Network Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "logan@mancuso.in"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(803) 470-3985"
resume_contact_address:         "South Carolina"

resume_header_contact_info:     "South Carolina • (803) 470-3985 • logan@mancuso.in"
display_header_contact_info:    "true"

resume_header_intro: "<p>
  Welcome! My name is Logan and this is my website where I post my most 
  relevant work experience and display my technical knowledge. I speicalize 
  in Infrastrucuter as Code (IaC) and automations, primarily using 
  Terraform on AWS and Azure.
  </br> </br>
  My personal projects typically consist of solving automation problems.
  We are often faced with small repetitive tasks that could otherwise be 
  handed off to a machine. Most recently, I am implementing and contributing
  to the development of a Proxmox provider for Terraform. This project 
  consists of creating a cloud-init image using Packer. This image is 
  bootstrapped using the latest deployment of docker swarm and other related
  packages. From which Terraform deploys the cluster of vms, delegating one 
  as the manager node and two or more additional worker nodes. Implementing 
  tagging, custom applications can then be deployed to the swarm and allowed
  to scale as demand grows. 
  </br> </br>
  Some of the applications I am hosting are NextCloud, for managing my file
  synchronization, HomeAssistant for centralized home automation. Nginx Proxy
  Manager to maintain and publish my SSL certificates and encrypt the traffic 
  within my network. I also use Portainer as my orchestration engine with a 
  plan to shift to Rancher once I have ported my applications from 
  docker swarm to Kubernetes. 
  </p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://gitlab.com/loganmancuso"
  resume_linkedin_url:          "https://www.linkedin.com/in/mancuso-logan"
  resume_website_url:           "https://loganmancuso_public.gitlab.io/proxmox-wiki"
resume_print_social_links:      true

# Design settings
resume_theme:                   dark

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
