source "https://rubygems.org"

gem 'github-pages'
# this gem provides regeneration support improvements on Windows
gem 'wdm', '>= 0.2.0' if Gem.win_platform?
gem "webrick", "~> 1.9.1"
gem "nokogiri", ">= 1.18.3"